#
# Copyright (c) 2019-2020 Intel Corporation.
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.
#
float32 tire_friction
float32 damping_rate
float32 max_steer_angle
float32 radius
float32 max_brake_torque
float32 max_handbrake_torque
float32 long_stiff_value
float32 lat_stiff_max_load
float32 lat_stiff_value
geometry_msgs/Vector3 position
