#
# Copyright (c) 2020 Intel Corporation.
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.
#

string type
string id
diagnostic_msgs/KeyValue attributes
geometry_msgs/pose transform
uint32 attach_to
---
int32 id
string error_string
