name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check
      run: make check

  ros:
    runs-on: ubuntu-latest
    container: ros:${{ matrix.ros-version }}-robot
    strategy:
      matrix:
        ros-version: [melodic, noetic]
    steps:
    - uses: actions/checkout@v2
    - name: Init Workspace
      run: |
        mkdir -p $GITHUB_WORKSPACE/../catkin_ws/src
        cd $GITHUB_WORKSPACE/../catkin_ws/src
        ln -s $GITHUB_WORKSPACE
        cd ..
        catkin init
    - name: Build, Test, Lint
      shell: bash
      run: |
        source /opt/ros/${{ matrix.ros-version }}/setup.bash
        cd $GITHUB_WORKSPACE/../catkin_ws &&
        catkin build --summarize --no-status --force-color
